development:
  adapter: postgresql
  encoding: unicode
  database: jamesmk_dev
  pool: 5
  username: james
  password: 
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: jamesmk_test
  pool: 5
  username: james
  password: 
  host: localhost
