development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: f3_development
#   pool: 5
#   username: f3
#   password: 

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: f3
#   pool: 5
#   username: f3
#   password: 

production:
  adapter: postgresql
  encoding: unicode
  database: f3
  pool: 5